apiVersion: apps/v1
kind: Deployment
metadata:
  name: focusflow-backend
  namespace: focusflow
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: focusflow-backend
  template:
    metadata:
      labels:
        app: focusflow-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/focusflow"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
