backend:
  replicaCount: 1

  image:
    repository: us-central1-docker.pkg.dev/focus-flow-508619/focusflow/focusflow-backend
    tag: latest
    pullPolicy: Always

  service:
    port: 5000

frontend:
  replicaCount: 2

  image:
    repository: us-central1-docker.pkg.dev/focus-flow-508619/focusflow/focusflow-frontend
    tag: latest
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80

mongo:
  image:
    repository: mongo
    tag: "6.0.26"
    pullPolicy: IfNotPresent

  service:
    port: 27017

  persistence:
    size: 5Gi
